### PR TITLE
Fix status for ghosted player

### PR DESCRIPTION
**Pull request by p3lim**
When the player (yourself) releases spirit during a resurrect cast by another player, LRI does not track the status of incoming resurrects.
For single spells it outright cancels them (`UNIT_SPELLCAST_STOP` or `UNIT_SPELLCAST_INTERRUPTED` handles that), but massres spells still go through, and they never end up finishing for the ghosted player, leaving them with a stuck status.

This commit resolves this by properly finishing it by listening to `RESURRECT_REQUEST`, catching the source resurrectee, clearing the appropriate data and firing callbacks.

As an added bonus, this commit also flags the ghosted player (still yourself) with `hasPending`.
Sadly, `UNIT_FLAGS` doesn't trigger for these situations, so we register `UNIT_HEALTH` until the player is considered alive by the client, clearing everything and firing callbacks.
Also, we can't detect if the player cancels this resurrect (no events, but we could perhaps hook the popup if we _really_ want).

### CODE REVIEW

**Comment by Phanx** [comment]
There's no way even with hooks to detect if other players cancel *their* resurrects, so the current behavior is at least consistent.

**Comment by p3lim** [comment]
If everyone had the addon the addon could communicate, but I'm not sure if it's feasible to add support for that.

**Comment by Phanx** [comment]
Avoiding comms was kind of the main motivation for writing the library in the first place.

I don't think cancelling the res dialog is a common enough issue to really matter. If you accidentally the button, you're probably going to speak up and ask for another res anyway.

**Comment by p3lim** [comment]
Nah, maybe some day blizzard adds an event for it.

**Pull request merged**
